import { NextResponse } from "next/server"

export async function GET() {
  const creators = [
    {
      id: "1",
      name: "Jordan Hayes",
      category: "Portrait",
      avatar: "/studio-portrait.png",
      wishlist: 160,
      rating: 4.9,
      price: 18,
      verified: true,
    },
    {
      id: "2",
      name: "Alex Chen",
      category: "Nature",
      avatar: "/nature-mountain-lake.png",
      wishlist: 95,
      rating: 4.8,
      price: 12,
      verified: true,
    },
    {
      id: "3",
      name: "Maria Rodriguez",
      category: "Architecture",
      avatar: "/modern-architecture-cityscape.png",
      wishlist: 110,
      rating: 4.9,
      price: 22,
    },
    {
      id: "4",
      name: "David Kim",
      category: "Portrait",
      avatar: "/fashion-portrait.png",
      wishlist: 75,
      rating: 4.7,
      price: 15,
    },
    {
      id: "5",
      name: "Emma Wilson",
      category: "Street",
      avatar: "/street-photography-night.png",
      wishlist: 120,
      rating: 4.6,
      price: 9,
    },
    {
      id: "6",
      name: "Noah Patel",
      category: "Nature",
      avatar: "/forest-mist.png",
      wishlist: 142,
      rating: 4.8,
      price: 19,
      verified: true,
    },
    {
      id: "7",
      name: "Sofia Nguyen",
      category: "Architecture",
      avatar: "/glass-tower.png",
      wishlist: 83,
      rating: 4.7,
      price: 27,
    },
    {
      id: "8",
      name: "Liam Johnson",
      category: "Street",
      avatar: "/urban-crosswalk.png",
      wishlist: 66,
      rating: 4.5,
      price: 11,
    },
    {
      id: "9",
      name: "Ava Brown",
      category: "Portrait",
      avatar: "/portrait-bokeh.png",
      wishlist: 210,
      rating: 5.0,
      price: 29,
      verified: true,
    },
    {
      id: "10",
      name: "Ethan Scott",
      category: "Nature",
      avatar: "/lush-forest-waterfall.png",
      wishlist: 54,
      rating: 4.3,
      price: 8,
    },
    {
      id: "11",
      name: "Maya Lopez",
      category: "Architecture",
      avatar: "/brutalist-building.png",
      wishlist: 132,
      rating: 4.8,
      price: 23,
    },
    {
      id: "12",
      name: "Oliver King",
      category: "Street",
      avatar: "/street-black-and-white.png",
      wishlist: 101,
      rating: 4.6,
      price: 14,
    },
  ]
  return NextResponse.json({ creators })
}
